-- Delete database if already existing and create a new one
DROP SCHEMA IF EXISTS eCommerce CASCADE;
CREATE SCHEMA eCommerce;

-- Create tables
BEGIN WORK;

CREATE TABLE USERS(
  id SMALLINT AUTO_INCREMENT,
  fullname VARCHAR(255) NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  "role" VARCHAR(255) NOT NULL,
  profile_pic VARCHAR(255),
CONSTRAINT PK_USER PRIMARY KEY(id),
CONSTRAINT CHECK_ROLE CHECK("role" IN('admin', 'employee'))
);

CREATE TABLE PRODUCTS(
  id SMALLINT AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  "description" VARCHAR(255) NOT NULL,
  price REAL NOT NULL,
  stock SMALLINT NOT NULL,
  quantity SMALLINT NOT NULL,
CONSTRAINT PK_PRODUCT PRIMARY KEY(id)
);

CREATE TABLE IMAGES(
  id SMALLINT AUTO_INCREMENT,
  product_id SMALLINT NOT NULL,
  "path" VARCHAR(255) NOT NULL,
CONSTRAINT PK_IMAGE PRIMARY KEY(id),
CONSTRAINT FK_PRODUCT FOREIGN KEY(product_id) REFERENCES PRODUCTS(id) ON DELETE CASCADE
);

COMMIT;

-- Insert data


